#!/bin/bash


mkdir -p logs

waitall() {
    for job in `jobs -p`
    do
        wait $job
    done
}


for wf_name in \
    SimpleReturnExample \
    ActivityReturnExample \
    SimpleDependencyExample \
    SequenceExample \
    MapReduceExample \
    DelayActivityExample \
    UnhandledErrorExample \
    HandledErrorExample \
    ErrorChainingExample \
    ErrorResultPassedExample \
    ErrorInWorkflowExample \
    TimeoutExample \
    SubworkflowExample
do
    echo $wf_name
    /usr/bin/env python -m flowy IntegrationTest $wf_name 77 &
    /usr/bin/env python runner.py > wlogs/$wf_name.log &
    waitall
done
